# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub, or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
            name: "Say hello"
            command: "echo Hello, World!"

# ****** Test Setup *****
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
      
    steps:
      - run: echo "1000"
      # - checkout
      - run: echo << pipeline.parameters.environment >>
      - run: echo << pipeline.parameters.manual >>
      - run: echo << pipeline.parameters.clients >>



parameters:
  environment:
    type: enum
    enum: [prod,staging]
    default: staging

  manual:
    type: boolean
    default: false

  clients:
    type: string

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  # say-hello-workflow:
  #   jobs:
  #     - say-hello

  build: 
    when: << pipeline.parameters.manual >>
    jobs:
      - build
            # tags:
            #   only: /^release-.*/
